#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biciclefastapi-deployment
spec:
  selector:
    matchLabels:
      app: biciclefastapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: biciclefastapi-server
    spec:
      containers:
      - name: biciclefastapi-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/btoarriola/biciclefastapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: biciclefastapi-service
  name: biciclefastapi-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: biciclefastapi-server
  type: LoadBalancer